### ISSUE TITLE
Grey screen on Windows

### ISSUE THREAD

**Issue by Simonx22** [PSI-Rockin/CorgiDS#6] opened 2017-12-23 20:43 UTC
Hello, I compiled CorgiDS on Windows, configured it and tried to load Mario Kart DS but it's just showing me a grey screen. I also tried on Ubuntu but it works fine without issues there.

![image](https://user-images.githubusercontent.com/26326692/34322541-ca735670-e829-11e7-86aa-862c5cd7bc02.png)

**Comment by PSI-Rockin** [comment] 2017-12-23 21:32
Press '0' (without quotes) and load the ROM, and check if the console outputs a huge blob of disassembly instructions during execution. (Don't worry if some say "UNDEFINED", the disassembler isn't complete yet)
If yes, that means the emulation thread is running fine. If no, there's a threading issue...

**Comment by Simonx22** [comment] 2017-12-23 21:41
@PSI-Rockin looks like the emulation thread runs fine:
```
(9A)[$020009A8] {$AAFFFFFB} -  bge $0x2000994
(9A)[$0200099C] {$E7D20007} -  ldrb r0, [r2, ???]
(9A)[$020009A0] {$E5620001} -  strb r0, [r2, #0x1]!
(9A)[$020009A4] {$E25CC010} -  subs ip, ip, #0x10
(9A)[$020009A8] {$AAFFFFFB} -  bge $0x2000994
(9A)[$0200099C] {$E7D20007} -  ldrb r0, [r2, ???]
(9A)[$020009A0] {$E5620001} -  strb r0, [r2, #0x1]!
(9A)[$020009A4] {$E25CC010} -  subs ip, ip, #0x10
(9A)[$020009A8] {$AAFFFFFB} -  bge $0x2000994
(9A)[$0200099C] {$E7D20007} -  ldrb r0, [r2, ???]
```

**Comment by PSI-Rockin** [comment] 2017-12-23 21:44
Yeah, that looks good.
I'm going to create a new branch for fixing these Windows GUI issues, starting with disabling touchscreen input and framebuffer output.
EDIT: Check out the "fix_windows" branch.

**Comment by Simonx22** [comment] 2017-12-23 22:00
@PSI-Rockin it's doing that now: 
![image](https://user-images.githubusercontent.com/26326692/34322925-f558c70c-e834-11e7-9130-ac57f49af1bb.png)

**Comment by PSI-Rockin** [comment] 2017-12-23 22:01
Alright, I've disabled threading as well, so the emulation isn't running.
Are you able to select options in the menubar using the mouse?

**Comment by Simonx22** [comment] 2017-12-23 22:04
Nope, I still need to use alt + F.

**Comment by PSI-Rockin** [comment] 2017-12-23 22:11
Okay, made some more changes to fix_windows.
I'm definitely investing in a Windows machine after this.

**Comment by Simonx22** [comment] 2017-12-23 22:15
Now it works!

**Comment by PSI-Rockin** [comment] 2017-12-23 22:22
Okay, so that means the problem is with how CorgiDS draws things.
The current process is incredibly hacky. At the beginning of the program, CorgiDS defines two QLabels that are each the size of one DS screen (256x192). Once the emulation thread has finished the framebuffers for the screen, the GUI thread converts the buffers into QImages, which are converted to QPixmaps, which are then attached to the QLabels that then display the final image.

I think the problem is that for some reason, the QLabels are interfering with the rest of the GUI. I haven't found any good resources for the proper way of drawing framebuffers to the screen, so I'll have to look into this one some more.

EDIT: Think I found a way to use paintEvents. Let's see if that works.

**Comment by PSI-Rockin** [comment] 2017-12-23 23:13
I've implemented a new method of drawing to the screen and have re-enabled everything else. Could you check fix_windows again?

**Comment by Simonx22** [comment] 2017-12-23 23:18
Still grey sadly. But the mouse navigation still works.
![image](https://user-images.githubusercontent.com/26326692/34323237-e7574b78-e83f-11e7-925c-59dbfb098212.png)

**Comment by PSI-Rockin** [comment] 2017-12-23 23:27
Is the screen gray on start-up, or does it only turn gray when you load a ROM? When starting up the program, it should be black.

**Comment by Simonx22** [comment] 2017-12-23 23:28
It's only grey when I load a ROM. It's black without a ROM.

**Comment by PSI-Rockin** [comment] 2017-12-23 23:38
Sounds like a problem during the image conversion process. I think that's what's happening as someone else was able to run Mario Kart on Windows.

Maybe it's a problem with the image format? It's using ARGB32 right now. I've sent in a commit that changes the format to RGB32, so see what happens.

**Comment by Simonx22** [comment] 2017-12-23 23:40
The same as before, sadly.

**Comment by PSI-Rockin** [comment] 2017-12-24 00:02
Not sure what could be happening. I'll look into it some more, but I'd like to see how other Windows systems fare.

Which version of Windows are you using? The other guy was using Windows 7.

**Comment by Simonx22** [comment] 2017-12-24 00:05
I'm using Windows 10.

**Comment by PSI-Rockin** [comment] 2017-12-24 00:52
I added some debugging code to paintEvent(), send a screenshot of what you see on the console.

**Comment by Simonx22** [comment] 2017-12-24 01:01
![image](https://user-images.githubusercontent.com/26326692/34323538-5a3a677a-e84e-11e7-8545-47a87d75ed99.png)

**Comment by PSI-Rockin** [comment] 2017-12-24 01:24
That's what it needs to be...
I added more debugging statements; they check if the format is incorrect and if the image is grayscale. It also draws a white dot in the middle of the upper screen.

**Comment by Simonx22** [comment] 2017-12-24 01:31
![image](https://user-images.githubusercontent.com/26326692/34323612-58caba08-e852-11e7-9f8f-7dfdfad9c94f.png)
I will continue testing tomorrow when I wake up, just tell me what to do.

**Comment by PSI-Rockin** [comment] 2017-12-24 01:50
Alright, thanks for your help today.

So, the format is correct, but the image is still gray. Either way, something's going wrong with converting the framebuffer to a QImage. Or maybe there's an issue with the framebuffer itself?

Anyway, I've removed some statements and added another one that displays the color data of the first ten pixels in the upper screen. If they're all gray during execution, the problem lies with the framebuffer. If not, the problem is the conversion.

**Comment by RyanHagood** [comment] 2017-12-24 02:03
The color data appears to be all grey still.
![uvho4ln](https://user-images.githubusercontent.com/15636848/34323722-7a7a031c-e824-11e7-9241-1e6c799d0805.png)

**Comment by PSI-Rockin** [comment] 2017-12-24 02:25
Alright, I've added some color data debugging statements deeper in the emulator core. What does that display?

**Comment by RyanHagood** [comment] 2017-12-24 02:28
It appears to do the same still.
![image](https://user-images.githubusercontent.com/15636848/34323832-1448facc-e828-11e7-8f38-8d0da467cb35.png)

**Comment by PSI-Rockin** [comment] 2017-12-24 02:37
Now that's weird. Means there's some sort of problem in the emulation itself.

I've added another debug statement that prints out the color data when the scanline is first drawn.

**Comment by RyanHagood** [comment] 2017-12-24 02:42
Below is the debug data on the console. I closed the emulation so I could scroll up on the terminal to get the initial lines:

![image](https://user-images.githubusercontent.com/15636848/34323893-245537ee-e82a-11e7-85bf-bccbe1d130b2.png)

**Comment by PSI-Rockin** [comment] 2017-12-24 02:45
Those values reflect how it should look, at least in the beginning of execution. What about the values later on in emulation?

**Comment by RyanHagood** [comment] 2017-12-24 02:48
It continues just repeating the same thing. I pressed keys and clicked stuff but it never appeared to change any further.
![image](https://user-images.githubusercontent.com/15636848/34323911-d8df490c-e82a-11e7-81ba-6287dcdc3b1f.png)

**Comment by PSI-Rockin** [comment] 2017-12-24 02:54
Well, looks like you've got a White Screen of Death. For whatever reason, Mario Kart isn't booting.

To confirm this, you can press '0' several seconds after execution and look at the disassembly. If it's getting stuck at a few memory addresses, we have a problem.

What are the exact sizes of your BIOS and firmware files?

**Comment by RyanHagood** [comment] 2017-12-24 03:02
This also occurs currently on Pokemon Mystery Dungeon as well with the same numbers.
![image](https://user-images.githubusercontent.com/15636848/34323977-f1d913d2-e82c-11e7-8457-3f323928da15.png)
![image](https://user-images.githubusercontent.com/15636848/34323973-d4be30ca-e82c-11e7-810d-ed44e184dbb0.png)
![image](https://user-images.githubusercontent.com/15636848/34323974-e1aad0d6-e82c-11e7-9ebb-c5f19dbc81e4.png)

**Comment by PSI-Rockin** [comment] 2017-12-24 03:05
Wait several seconds after starting the ROM and press '0'. What does the disassembly show?

**Comment by RyanHagood** [comment] 2017-12-24 03:11
Pressing 0 isn't doing anything for me.

**Comment by PSI-Rockin** [comment] 2017-12-24 03:15
Weird. I added something that should make the program automatically disassemble after loading a ROM.

You may have to wait a little bit; logging every executed instruction is going to be slow. But see what happens after something like half a minute of waiting. Especially keep an eye out for if it stops disassembling all of a sudden.

**Comment by RyanHagood** [comment] 2017-12-24 03:41
On Windows we might want it to be logging the disassembly to a file as opposed to the console window since the buffers are fairly small on Windows for that. Here is what I had on the terminal after waiting ~30 seconds and pressing 0 now. After that the emulator crashed and when I opened it with Visual Studio it gave me:
Exception thrown: write access violation.
VRAM_dest was 0x111011101118112.
on line 1109 of gpueng.cpp.

https://pastebin.com/y230HHep

**Comment by PSI-Rockin** [comment] 2017-12-24 03:55
Not sure how this passed me, but I forgot to reset the display capture unit after loading a ROM; that's where the access violation above is coming from. Added something to do that. What happens when you run it now?

**Comment by RyanHagood** [comment] 2017-12-24 04:00
I am now instantly upon loading a rom getting the unrecognized capture source as seen in the output below:

ARM9 BIOS loaded successfully.
ARM7 BIOS loaded successfully.

Stored CRC: $597E
Calc CRC: $597E
FW: USER0 CRC16 = GOOD
Stored CRC: $F098
Calc CRC: $F098
FW: USER1 CRC16 = GOODFailed to load
QWindowsNativeFileDialogBase::onSelectionChange () 0
QWindowsNativeFileDialogBase::onSelectionChange () 0
QWindowsNativeFileDialogBase::onSelectionChange (QUrl("file:///C:/Users/Daisa/Desktop/MarioKart/mariokart.nds")) 1
C:/Users/Daisa/Desktop/MarioKart/mariokart.nds successfully loaded
Allocating 33554432 bytes for ROM...
Allocated memory successfully.
Loading ROM into memory...

POWCNT1: $820F
A9 offset: $00004000 entry: $02000800 RAM: $02000000 size: $000E7534
A7 offset: $00141600 entry: $02380000 RAM: $02380000 size: $000289A4

ITCM size: $00000000
DTCM base: $027E0000
DTCM size: $00000000
Color data on scanline 0: $FFF3F3F3
Color data on scanline 0: $FFF3F3F3
Color data on scanline 0: $FFF3F3F3
Color data on scanline 0: $FFF3F3F3
Color data on scanline 0: $FFF3F3F3
Unrecognized capture source -842150451

**Comment by PSI-Rockin** [comment] 2017-12-24 04:03
Made a small fix to only allow capture for engine A (I presume capture was happening for engine B inadvertently). What happens now?

**Comment by RyanHagood** [comment] 2017-12-24 04:18
It now appears to be back to where it was previously:
![image](https://user-images.githubusercontent.com/15636848/34324179-010a6cac-e837-11e7-9215-c22c0ceee88b.png)

I did notice that if I load the rom, then hit 0, then load the rom again I get a different output:
![image](https://user-images.githubusercontent.com/15636848/34324198-8f8f96e6-e837-11e7-908a-aecdc11a1be1.png)

Not sure how relevant that is to you.

**Comment by PSI-Rockin** [comment] 2017-12-24 04:31
That sequence of code happens normally in execution.

Okay, I changed some of the debugging stuff. Run it for around a minute and see what the console spits out.

**Comment by Simonx22** [comment] 2017-12-24 10:09
I did let it run for like one minute:
![image](https://user-images.githubusercontent.com/26326692/34325731-b6bb5ff8-e89a-11e7-95d9-98677187eb79.png)
Edit: [Pastebin log](https://pastebin.com/iDEniGxU)

**Comment by puigru** [comment] 2017-12-24 16:23
It works if you compile it with mingw53_32. The master branch works, you just have to use the Alt keys to navigate the menus. This is fixed by commit 6154a029ce8aceb3ef38ac65a71abff707591340, I think the issue had to do with the screen widgets and menu overlapping with one another.

![corgids](https://user-images.githubusercontent.com/7153662/34327815-a827fbb6-e8ce-11e7-9025-6216f8e8e90b.png)

I've uploaded a working build for [master](https://drive.google.com/open?id=10jnuIubndy5eO6marH84Qtsy_HdaJ5ui) and the [aforementioned commit](https://drive.google.com/open?id=1g8OKKZJkT7vvak9VhI3w9r9TrJS5rJFg).

**Comment by PSI-Rockin** [comment] 2017-12-24 16:56
I think what's happening is that something isn't getting initialized properly, so for some people booting a game works and for others it doesn't.

For those who get a gray screen: disable "Directly boot game ROM" in the config window and try running a game without disassembly. This will force a boot-up through the BIOS, which is how you'd normally boot-up with a real DS. Report what happens.

**Comment by puigru** [comment] 2017-12-24 16:58
I consistently got a gray screen when compiling with msvc2017_64 instead of mingw53_32.

**Comment by PSI-Rockin** [comment] 2017-12-24 17:41
@XXLuigiMario If it's a compiler problem, then I have no leads. I'd need to get a Windows machine myself to see what Visual Studio doesn't like.

However, I'd still like to see how booting from the BIOS works. If that makes the game, or even the firmware, run correctly, then I at least have an idea of what's going on (not initializing everything properly). Otherwise, we'll have to use different compilers for the time being.

**Comment by puigru** [comment] 2017-12-24 17:51
@PSI-Rockin Booting from BIOS does work on my end. I have no problem using mingw53_32 over msvc2017_64. I actually chose the second one accidentally while testing and noticed It wouldn't get past the gray screen.

![window](https://user-images.githubusercontent.com/7153662/34328249-e2ca871e-e8da-11e7-822d-ea7382872723.png)

**Comment by PSI-Rockin** [comment] 2017-12-24 17:54
Does it run the game correctly?

**Comment by puigru** [comment] 2017-12-24 17:56
Yes, I've not actually tried the "Directly boot game ROM" option yet. I took the screenshot of Mario Kart's menu after booting from the BIOS.

Edit: A word

**Comment by Simonx22** [comment] 2017-12-24 19:22
I will try to compile later with mingw. Booting the BIOS doesn't work with msvc2017.

**Comment by PSI-Rockin** [comment] 2017-12-24 21:57
If mingw works, I'll just have to distribute builds from that for the time being until I can figure out what's going wrong with Visual Studio.

Could someone build a 64-bit version using mingw and check what happens?

**Comment by Simonx22** [comment] 2017-12-25 02:36
I tried to build with Appveyor and mingw53_32 but it [didn't work](https://ci.appveyor.com/project/Simonx22/corgids/build/1.0.15#L1820). I'm not sure if this is an issue on my side.

**Comment by PSI-Rockin** [comment] 2017-12-25 02:55
@Simonx22 bios.cpp doesn't include stdio, and it looks like mingw doesn't like that. You can just comment out the "printf" statements, as that file's not too important right now. Sorry about that.

**Comment by Simonx22** [comment] 2017-12-25 03:30
Ah, that worked, thanks. I will try to make artifacts working tomorrow.

**Comment by DeeKayHT** [comment] 2017-12-25 06:44
My apologies, how are you guys able to work with the Qt dependency? I don't have any experience with integrating it with Visual Studio.

**Comment by Simonx22** [comment] 2017-12-25 16:05
Alright, I got it working with mingw32. It works on both master and fix_windows, though fix_windows is a bit slower of course due to debug things I guess, but using the mouse in the GUI works fine, I don't know how to compile Qt 5.9 with mingw64. I tried to search but can only find how to compile for older Qt versions. So as of right now, CorgiDS only works with mingw32 on Windows. Also, "Directly boot game ROM" works fine.

**Comment by PSI-Rockin** [comment] 2017-12-25 16:47
So the issue is indeed with Visual Studio. I'll need to update the README to reflect that.

I've merged fix_windows with master, so the menubar should be fixed. It's unfortunate we couldn't figure out what was wrong with Visual Studio. Apparently it's possible to set up a Windows 10 VM for free, so I could try to look into the issue that way, but it's going to take a while to set everything up.

Thank you guys for your time and patience!

**Closed as completed by PSI-Rockin** 2017-12-25 16:47 UTC
